
--동물 카테고리
INSERT INTO RCATEGORY (rCATEGORYID, rCATEGORYNAME) VALUES (RCATE_SEQ.NEXTVAL , '강아지');
INSERT INTO RCATEGORY (rCATEGORYID, rCATEGORYNAME) VALUES (RCATE_SEQ.NEXTVAL , '고양이');
INSERT INTO RCATEGORY (rCATEGORYID, rCATEGORYNAME) VALUES (RCATE_SEQ.NEXTVAL , '토끼');
INSERT INTO RCATEGORY (rCATEGORYID, rCATEGORYNAME) VALUES (RCATE_SEQ.NEXTVAL , '고슴도치');
INSERT INTO RCATEGORY (rCATEGORYID, rCATEGORYNAME) VALUES (RCATE_SEQ.NEXTVAL , '햄스터');
INSERT INTO RCATEGORY (rCATEGORYID, rCATEGORYNAME) VALUES (RCATE_SEQ.NEXTVAL , '24시간');
--증상 카테고리
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '눈');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '코');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '입');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '귀');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '피부');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '구강');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '다리');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '숨소리');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '행동');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '음식섭취');
INSERT INTO SCATEGORY (sCATEGORYID, sCATEGORYNAME) VALUES (SYMPTOM_SEQ.NEXTVAL , '소화기');
